config/routes.rb
Rails.application.routes.draw do
  root 'static#welcome'
  get  '/login', :to => 'sessions#new', :as => :login
  post '/login', :to => 'sessions#create'
  get 'auth/google_oauth2/callback', :to => 'sessions#create'
  get '/auth/failure', :to => 'sessions#failure'
  delete '/logout', to: 'sessions#destroy', as: 'logout'
  get '/admin/login', to: 'sessions#new', :as => :admin_login
  post '/admin/pets', to: 'admin/pets#create', :as => :admin_pet_create
  patch '/admin/pets/:id(.:format)', to: 'admin/pets#update', :as => :admin_pet_update
  get '/users/:user_id/pets', to: 'pets#mypets', :as => :my_pet_index

  resources :pets, only: [:index]

  namespace :admin do
    resources :pets
    resources :breeds
  end

  resources :pets do
    resources :adoptions, only: [:new, :create]
  end


  resources :users do
    resources :pets, only: [:show, :edit, :update]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ActiveRecord::Base
  include Titleize
  include Displayname
  has_secure_password
  has_many :adoptions
  has_many :pets, through: :adoptions
  #validates :phone_number, length: { is: 10 }
  validates_format_of :phone_number, with: /\A(\d{10}|\(?\d{3}\)?[-. ]\d{3}[-.]\d{4})\z/, unless: -> { from_omniauth? }
  validates :name, presence: true
  validates :email, presence: true
  validates :email, uniqueness: true
  before_save :tileize_name
  before_create :tileize_name

  def from_omniauth?
    provider && uid
  end

  def phone_number=(phone_number)
    super(phone_number.blank? ? nil : phone_number.gsub(/[^\w\s]/, ''))
  end

  def self.find_or_create_from_auth_hash(auth)
  		where(provider: auth.provider, uid: auth.uid).first_or_initialize.tap do |user|
  			user.provider = auth.provider
  			user.uid = auth.uid
  			user.name = auth.info.name
        user.email = auth.info.email
        user.password = SecureRandom.urlsafe_base64
  			user.save!
  		end
    end

  def find_adoption_by_pet(pet)
    self.adoptions.each do |adoption|
      if adoption.pet_id == pet.id
        return adoption
      end
    end
  end

end

app/controllers/users/users_controller.rb
class Users < ApplicationController

  def new
  end

  def create
  end

  def show
  end 

  def edit
  end

  def update
  end


  def destroy
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :user_authenticate, only: [:show, :edit]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
    session[:user_id] = @user.id
    flash[:notice] = "Account successfully created!"
    redirect_to user_path(@user)
  else
    render :new
      end
  end


  def show
    user = current_user
    respond_to do |format|
      format.html { render :show }
      format.json { render json: user, status: 200 }
    end 
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    @user.assign_attributes(user_params)
    if @user.valid?
      @user.save(user_params)
      redirect_to user_path(current_user)
    else
      render :edit
    end
  end


  def destroy
    session.clear
    redirect_to root_url
  end

private

def user_params
  params.require(:user).permit(:email, :name, :phone_number, :password, :password_confirmation)
end

end

app/helpers/users_helper.rb
module UsersHelper

  def number_format(phone_number)
    int_num = phone_number.to_i
    formatted_number = number_to_phone(int_num, area_code: true)
    return formatted_number
  end
end

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
    <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2>
    <%= pluralize(@user.errors.count, "error") %>
    prohibited this user from being saved:
  </h2>

  <ul>
  <% @user.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
  <% end %>
  <%end%>
  </ul>
</div>
<div class="col-sm-4">
<%= f.label :name %>
<%= f.text_field :name %>
<br>
<%= f.label :password %>
<%= f.password_field :password %>
<br>
<%= f.label :password_confirmation %>
<%= f.password_field :password_confirmation %>
<br>
<%= f.label :email %>
<%= f.email_field :email %>
<br>
<%= f.label :phone_number %>
<%= f.telephone_field :phone_number %>
<br>
<%= f.submit  "Create User" %>
<%end%>
</div>

app/views/users/edit.html.erb
<div id="error_explanation">
  <h2>
    <% if @user.errors.count > 0 %>
    <%= pluralize(@user.errors.count, "error") %>
    prohibited this user from being saved:
  </h2>

  <ul>
  <% @user.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
  <% end %>
  <%end%>
  </ul>
</div>
<h1> Edit Profile </h1>
<%= form_for current_user do |f| %>
<%= f.label :name %>
<%= f.text_field :name %>
<br>
<%= f.label :email %>
<%= f.email_field :email %>
<br>
<%= f.label :phone_number %>
<%= f.telephone_field :phone_number %>
<br>
<%= f.submit  "Update Profile" %>
<%end%>

app/views/users/new.html.erb
<h1>Sign Up</h1>
<%= render 'form' %>

app/views/users/show.html.erb
<h2>Name: <%= current_user.name %></h2>
<br>
<h4>Email: <%= current_user.email %></h4>
<br>
<h4>Phone Number: <%= number_format(current_user.phone_number) %></h4>
<br>

<p>Need to make any changes? <%=link_to 'Update Profile', edit_user_path(current_user)%></p>