config/routes.rb
Rails.application.routes.draw do
  root 'static#welcome'
  get  '/login', :to => 'sessions#new', :as => :login
  post '/login', :to => 'sessions#create'
  get 'auth/google_oauth2/callback', :to => 'sessions#create'
  get '/auth/failure', :to => 'sessions#failure'
  delete '/logout', to: 'sessions#destroy', as: 'logout'
  get '/admin/login', to: 'sessions#new', :as => :admin_login
  post '/admin/pets', to: 'admin/pets#create', :as => :admin_pet_create
  patch '/admin/pets/:id(.:format)', to: 'admin/pets#update', :as => :admin_pet_update
  get '/users/:user_id/pets', to: 'pets#mypets', :as => :my_pet_index

  resources :pets, only: [:index]

  namespace :admin do
    resources :pets
    resources :breeds
  end

  resources :pets do
    resources :adoptions, only: [:new, :create]
  end


  resources :users do
    resources :pets, only: [:show, :edit, :update]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/pet.rb
class Pet < ActiveRecord::Base
  include Titleize
  include Displayname
  has_many :adoptions
  has_many :users, through: :adoptions
  has_many :pet_breeds
  has_many :breeds, through: :pet_breeds
  accepts_nested_attributes_for :breeds
  validates :name, presence: true
  validates :age, presence: true
  validates_inclusion_of :age, :in => 1..30
  before_save :tileize_name
  before_create :tileize_name

  def breed_attributes=(breed_attributes)
      if breed_attributes[:name] != ""
      breed = Breed.find_or_create_by(breed_attributes)
      self.breeds << breed
    end
  end

  def display_breed
    if self.breeds.count > 1
      names = []
      self.breeds.each do |breed|
        names << breed.name
      end
      names.map(&:inspect).join('/').delete('"')
    else
      self.breeds.each do |breed|
        return breed.name
      end
    end
  end
  #Class Scope Method
  def self.from_breed(breed)
    params = breed.name
    Pet.joins(:breeds).where({"breeds.name" => params })
  end

  #Class Scope Method
  def self.without_owner
    Pet.joins('left outer join adoptions on adoptions.pet_id = pets.id').where('adoptions.id is null')
  end

  def display_ownership
    if self.users.count == 0
      return "N"
    else
      return "Y"
    end
  end


end

app/controllers/admin/pets_controller.rb
class Admin::PetsController < ApplicationController
  before_action :admin_authenticate
  before_action :find_pet, only: [:show, :edit, :update]

  def index
    pets = Pet.all.order(:name)
    #Class Scope Method
    respond_to do |format|
      format.html { render :index }
      format.json { render json: pets, status: 200 }
    end 
  end

  def new
    @pet = Pet.new
  end

  def create
    @pet = Pet.create(pet_params)
    render json: @pet, status: 201
    if !@pet.save
      render :new
      #error for pet being invalid
    end
  end

  def show
    pet = Pet.find_by(id: params[:id])
    render json: pet, status: 200
  end

  def edit
    #@pet = Pet.find_by(id: params[:id])
    #find_pet
  end

  def update
    #@pet = Pet.find_by(id: params[:id])
    @pet.assign_attributes(pet_params)
    if @pet.valid?
      @pet.save(pet_params)
      flash[:notice] = "#{@pet.name} successfully updated!"
      redirect_to admin_pets_path
    else
      render :edit
    end
  end

  def destroy
  end

private
def pet_params
  params.require(:pet).permit(:name, :age, breed_ids:[], breed_attributes: [:name])
end

def find_pet
  @pet = Pet.find_by(id: params[:id])
end



end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  before_action :user_authenticate

  def index
      pets = Pet.without_owner.sort_by(&:name)
      respond_to do |format|
        format.html { render :index }
        format.json { render json: pets, status: 200 }
    end
  end

  def mypets
    if params[:user_id] != nil && current_user == User.find_by(id: params[:user_id])
      user_pets = current_user.pets
      respond_to do |format|
        format.html { render :mypets }
        format.json { render json: user_pets, status: 200 }
      end
    else
      redirect_to user_path(current_user)
    end
  end 

  def show
    @pet = Pet.find_by(id: params[:id])
    render json: @pet, status: 200
  end 

  def edit
      @pet = Pet.find_by(id: params[:id])
      @pet.users.each do |user|
        redirect_to root_path unless user.id == current_user.id
      end
  end

  def update
    pet = Pet.find_by(id: params[:id])
    pet.update(pet_params)
    redirect_to my_pet_index_url(current_user)
  end

private

def pet_params
  params.require(:pet).permit(:name)
end


end

app/views/admin/pets/edit.html.erb
<% if @pet.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@pet.errors.count, "error") %>
      prohibited this pet from being saved:
    </h2>

    <ul>
    <% @pet.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<h1> Edit <%= @pet.display_name%> Info </h1>


<%= form_for @pet, :url => admin_pet_update_path do |f| %>
<%= f.label :name %>
<%= f.text_field :name %>
<br>
<%= f.label :age %>
<%= f.number_field :age %>
<br>
<%= f.label :breed %>
<br>
<%= collection_check_boxes :pet, :breed_ids, Breed.all, :id, :name %>
<%= f.fields_for :breed_attributes, @pet.breeds.build do |breeds_fields| %>
<br>
<%= f.label "New breed?" %>
<%= breeds_fields.text_field :name %>
<br>
<%= f.submit "Update #{@pet.name}" %>
<% end %>
<% end %>

app/views/admin/pets/index.html.erb
<h1> Pet List </h1>
<p style="border:1px solid #ccc"></p>
<p><%= link_to " Add New Pet", new_admin_pet_path, :class => "btn col-sm-2"%> </p>
<script type="text/javascript" charset="utf-8">
    $(document).ready(adminPetsIndex);
    </script>
<div id="admin_pets_table"></div>

app/views/admin/pets/new.html.erb
<div id="created_pet">
</div>
<div id="pet_form">
<h1>Add New Pet </h1>
<% if @pet.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@pet.errors.count, "error") %>
      prohibited this pet from being saved:
    </h2>

    <ul>
    <% @pet.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_for @pet, :url => admin_pet_create_path do |f| %>
<%= f.label :name %>
<%= f.text_field :name %>
<br>
<%= f.label :age %>
<%= f.number_field :age %>
<br>
<%= collection_check_boxes :pet, :breed_ids, Breed.all, :id, :name do |b| %>
    <div> <%= b.check_box %><%= b.label { b.text } %></div>
    <% end %>
<br>
<%= f.fields_for :breed_attributes, @pet.breeds.build do |breeds_fields| %>
<br>
<%= f.label "New breed?" %>
<%= breeds_fields.text_field :name %>
<br>
<%= f.submit "Add Pet", id: "new_pet_button" %>
<% end %>
<% end %>
</div>
<script type="text/javascript" charset="utf-8">
    $(document).ready(addNewPet);
    </script>