config/routes.rb
Rails.application.routes.draw do
  root 'static#welcome'
  get  '/login', :to => 'sessions#new', :as => :login
  post '/login', :to => 'sessions#create'
  get 'auth/google_oauth2/callback', :to => 'sessions#create'
  get '/auth/failure', :to => 'sessions#failure'
  delete '/logout', to: 'sessions#destroy', as: 'logout'
  get '/admin/login', to: 'sessions#new', :as => :admin_login
  post '/admin/pets', to: 'admin/pets#create', :as => :admin_pet_create
  patch '/admin/pets/:id(.:format)', to: 'admin/pets#update', :as => :admin_pet_update
  get '/users/:user_id/pets', to: 'pets#mypets', :as => :my_pet_index

  resources :pets, only: [:index]

  namespace :admin do
    resources :pets
    resources :breeds
  end

  resources :pets do
    resources :adoptions, only: [:new, :create]
  end


  resources :users do
    resources :pets, only: [:show, :edit, :update]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_pets_table.html.erb
<% if @user_pets %>
<table style="width:100%">
  <tr>
    <th>Name</th>
    <th>Age</th>
    <th>Breed</th>
    <th>Adoption Date</th>
  </tr>
<% @user_pets.each do |pet| %>
  <tr>
  <td><%= pet.name %></td>
  <td><%= pet.age %></td>
  <td><%=pet.display_breed%></td>
  <% adoption = current_user.find_adoption_by_pet(pet) %>
  <td><%=adoption.adoption_date%></td>
  <%end%>
</tr>

<% else %>

<table style="width:100%">
  <tr>
    <th>Name</th>
    <th>Age</th>
    <th>Breed</th>
 <% if current_admin %>
    <th>Owned?</th>
    <%end%>
  </tr>
<% @pets.each do |pet| %>
  <tr>
  <td><%= pet.name %></td>
  <td><%= pet.age %></td>
  <td><%=pet.display_breed%></td>
  <% if current_admin %>
  <td><%=pet.display_ownership%></td>
  <% if pet.display_ownership == "N" %>
  <td><%= link_to "Edit Pet", edit_admin_pet_path(pet), :class => "btn col-sm-4" %></td>
  <%end%>
  <% else %>
  <td><%= link_to "Adopt?", new_pet_adoption_path(pet), :class => "btn col-sm-4" %></td>
  <%end%>
  <%end%>
</tr>
<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PawsitiveOutreach</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  </head>

  <body>
    <%if current_user %>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="/">Pawsitive Outreach</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarText">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link" href="/users/<%=current_user.id%>">Profile <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/users/<%=current_user.id%>/pets">My Pets</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/pets">View Available Pets</a>
      </li>
    </ul>
    <li class="nav-item">
     <%= link_to('Logout', logout_path, method: :delete, :class => "btn") %>
    </li>
  </div>
</nav>
  <%elsif current_admin %>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
<a class="navbar-brand" href="/">Pawsitive Outreach Admin Mode</a>
<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
  <span class="navbar-toggler-icon"></span>
</button>
<div class="collapse navbar-collapse" id="navbarText">
  <ul class="navbar-nav mr-auto">
    <li class="nav-item">
      <a class="nav-link" href="/admin/pets">Pets List <span class="sr-only">(current)</span></a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="/admin/breeds">Breeds List</a>
    </li>
  </ul>
  <li class="nav-item">
   <%= link_to('Logout', logout_path, method: :delete, :class => "btn") %>
  </li>
</div>
</nav>

  <%else%>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
<a class="navbar-brand" href="/">Pawsitive Outreach</a>
<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
  <span class="navbar-toggler-icon"></span>
</button>
<div class="collapse navbar-collapse" id="navbarText">
  <ul class="navbar-nav mr-auto">
    <% if !admin_page? %>
    <li class="nav-item">
      <a class="nav-link" href="users/new">Sign Up <span class="sr-only"></span></a>
    </li>
    <%end%>
    <li class="nav-item">
      <a class="nav-link" href="/login">Log In</a>
    </li>
    <ul>
    </div>
    </nav>
    <%end%>
    <% if flash[:notice] %>
      <div class="notice"><%= flash[:notice] %></div>
    <% end %>

    <%= yield %>
  </body>
</html>